### ISSUE TITLE
Huge memory leak while running yolo11n-pose model

### ISSUE THREAD

**Issue by Prajwal-SU** [dlstreamer/dlstreamer#461]
Hello,
I am running this below GStreamer pipeline,

GST_DEBUG=3 gst-launch-1.0 rtspsrc location=rtsp://localhost:8552/stream/0 ! decodebin ! videoconvert ! capsfilter caps="video/x-raw,format=BGR" ! queue max-size-buffers=1 leaky=no ! gvadetect model=/opt/kloudspot/vision/models/assets/yolo11n-pose.xml model-proc=/opt/kloudspot/vision/models/demographics/yolo_pose_proc.json device=CPU inference-interval=1 ! gvawatermark ! videoconvert ! queue max-size-buffers=1 leaky=no ! appsink max-buffers=1 drop=true

Memory is going up till 20gb. with just 3 to 4 people in frame.

Is there a any way to resolve this issue...

**Comment by Prajwal-SU** [comment]
OS --> ubuntu 22, ram--> 30GB, OpenVINO--> 2025.1.0-18503-6fec06580ab-releases/2025/1, gstreamer---> GStreamer Core Library version 1.24.12,

Updated pipeline--->
gst-launch-1.0 filesrc location=5min_2.mp4 ! qtdemux ! h264parse ! avdec_h264 ! gvadetect model=yolo11n-pose.xml model-proc=yolo_pose_proc.json device=CPU inference-interval=1 ! gvawatermark ! videoconvert ! autovideosink

original yolo 11n-pose model was first converted into "onnx" format then converted to openvino using this command (mo --input_model /home/best.onnx --reverse_input_channels True --scale_values [255,255,255] --output_dir /home/)

after minimizing the pipeline still I got the leak.

**Comment by Prajwal-SU** [comment]
I am using latest DL-Streamer v2025.0.1.3.

Regarding video, any public video is fine.

I have exported this "yolo11n-pose.pt" model using ultralytics with opset-version-11.
`from ultralytics import YOLO
model = YOLO('/home/yolo11n-pose.pt')
results = model.export(format='onnx', opset=11)`

I am attaching the model, its proc file and screenshot of warnings.

[yolo_pose_proc.json](https://github.com/user-attachments/files/19837283/yolo_pose_proc.json)
![Image](https://github.com/user-attachments/assets/e0e0b207-f77b-40fd-920f-27d76da9c64e)

[yolo11n-pose.zip](https://github.com/user-attachments/files/19837304/yolo11n-pose.zip)

**Comment by Prajwal-SU** [comment]
I am using pre-built docker container.

**Comment by Prajwal-SU** [comment]
Used yolo_v11_pose instead of yolo_v8_pose converter.

Yes, Ultralytics version was older before 8.3.70, now upgraded the ultralytics to 8.3.113 and converted to ONNX using the below code
`from ultralytics import YOLO
model = YOLO('/home/yolo11n-pose.pt')
results = model.export(format='onnx', opset=11)`
After that used this cmd /python3 -m openvino.tools.mo --input_model /home/yolo11n-pose.onnx --scale_values [255,255,255] --reverse_input_channels 
So, here we used openvino-2024.6.0 to convert into IR-format because "openvino.tools.mo" needed openvino-dev, so we dont have openvino-dev 2025, by default it will take openvino-2024.6.0.

Ran the pipeline for 5mins, 3GB memory was used and still it kept increasing.
I am running the pipeline in 2025.0.1.3-ubuntu22 docker, I am just checking the docker stats to calculate memory.

I am sharing all the models and proc-file again

[yolo11n-pose.zip](https://github.com/user-attachments/files/19851183/yolo11n-pose.zip)

**Comment by Prajwal-SU** [comment]
Hi @brmarkus, did you find any way to reduce memory usage.

**Comment by Prajwal-SU** [comment]
Hi @brmarkus, Could you please confirm how I should approach the dev-team or support-team for this? Should I create a new issue and categorize it as a performance issue, or is there a preferred way to escalate this?

**Comment by Prajwal-SU** [comment]
Hi @brmarkus and @nszczygl9 ,

Just following up on this issue —. If possible, could you kindly take a look or let me know the appropriate next steps to escalate this to the relevant team?

Your support on this would be greatly appreciated.

**Comment by tbujewsk** [comment]
Hi @brmarkus 
Thank you for your comments/information. We will add it to our internal issues list and aim to get back to you as soon as possible.

**Comment by tjanczak** [comment]
@Prajwal-SU and @brmarkus - we have reproduced the memory leak and we are validating the fix; we will let you know once the fix is available.

**Comment by tjanczak** [comment]
Please also note there is no need to use model-proc file if you use the model download script shipped along with DLStreamer:  
`>samples/download_public_models.sh yolo11n-pose`

The script stores required pre/post-processing information directly in OpenVINO model descriptor (*.xml) file, so one can use:  
`... ! gvadetect model=yolo11n-pose.xml ...`   (mode-proc parameter no longer needed)

**Comment by Prajwal-SU** [comment]
Hi @tbujewsk, 
Used this file >samples/download_public_models.sh to download the yolo11n-pose.xml 

Updated Pipeline-->
gst-launch-1.0 rtspsrc location=rtsp://10.90.6.141:32554/no_mask ! decodebin ! videoconvert ! capsfilter caps="video/x-raw,format=BGR" ! gvadetect model=yolo11n-pose.xml device=GPU inference-interval=1 pre-process-backend=opencv ! queue ! gvawatermark ! videoconvert ! appsink max-buffers=1 drop=true

There were around 8-10 people in frame.
Below I have attached graph image of memory leak and models.

![Image](https://github.com/user-attachments/assets/9daa6e42-de48-44b0-a519-6f4ac66cdbef)

[yolo-pose-FP.zip](https://github.com/user-attachments/files/20231918/yolo-pose-FP.zip)

**Comment by tjanczak** [comment]
The issue if fixed here: https://github.com/open-edge-platform/edge-ai-libraries/tree/main/libraries/dl-streamer

Please note DLStreamer is part of Intel Open Edge Platform now, and active development moved to the new location.

**Comment by tjanczak** [comment]
DLStreamer is still a separate/standalone component with own containers published on DockerHub. 
There is also a DLStreamer Pipeline Server (built on top of DLStreamer) with own container, which can be run as microservice. 
Both DLStreamer and DLStreamer Pipeline Server can be used separately - there is no tight coupling. 

We are still discussing how to facilitate migration to a new github location; any suggestions are welcome.

**Comment by Prajwal-SU** [comment]
Hi @brmarkus and @tjanczak ,
Thank you for providing fix.
I have performed a leak test on yolov11n pose in both dev and runtime docker with the provided fix, but I still see memory is increasing in slow pace.

Here is what I did,

On Ubuntu 22.04.2,

1. Pulled dev image  > docker pull intel/dlstreamer:2025.0.1.3-dev-ubuntu22. > docker run -it --privileged --net=host -d --device /dev/dri --group-add=109 -p 8081:8081 -v /tmp/.X11-unix -e DISPLAY=$DISPLAY -v /dev/shm/:/dev/shm -v /dev/bus/usb -v /home/prajwal/:/home/prajwal/ -v /opt/kloudspot/:/opt/kloudspot/ -v /var/log/:/var/log/ -v  /root/cl_cache/:/root/cl_cache/ -u root intel/dlstreamer:2025.0.1.3-dev-ubuntu22 /bin/bash.
2. Changed this file (/home/dlstreamer/dlstreamer/src/monolithic/gst/inference_elements/common/post_processor/converters/to_roi/blob_to_roi_converter.cpp) with provided fix.
3. source /opt/intel/openvino_2025.0.0/setupvars.sh
4. cd /home/dlstreamer/dlstreamer/
5. rm -rf build/*
6. cd build 
7. cmake ..
8. make -j 
9. Here we Used this file >samples/download_public_models.sh to download the yolo11n-pose.xml, then running the pipeline. > gst-launch-1.0 rtspsrc location=rtsp://10.90.9.149:32558/no_mask ! decodebin ! videoconvert ! capsfilter caps="video/x-raw,format=BGR" ! gvadetect model=yolo11n-pose.xml device=GPU inference-interval=1 pre-process-backend=opencv ! gvawatermark ! videoconvert ! appsink max-buffers=1 drop=true.
10. Ran the pipeline for approx 12hrs and plotted the graph of no_mask.mp4.

![Image](https://github.com/user-attachments/assets/e89d9ad4-909b-4ecb-82d3-f9b116941975)

Now for the runtime image, I just took libgstvideoanalytics.so and libinference_elements.a files from dev image which I build using above mentioned steps and replaced those two files in runtime image (/opt/intel/dlstreamer/build/intel64/Release/lib/). 
After performed memory leak test in runtime image with same video and same model and same pipeline.

![Image](https://github.com/user-attachments/assets/9e902d6e-60de-4bc5-abbe-1a4b8e6c9f72)

Here we used mediamtx server to run the video in rtspURL and FP16 model is used.
I am attaching the video, models used and these two files libgstvideoanalytics.so, libinference_elements.a

[dev_build_files, videos and models.zip](https://github.com/user-attachments/files/20383252/dev_build_files.videos.and.models.zip)

**Comment by Prajwal-SU** [comment]
Hi @tjanczak, 
Could you please look into this memory leak issue? We have observed that memory usage increases gradually with a single RTSP stream (it went from 200mb to 5gb and it still kept increasing) and grows exponentially as additional streams are added.

**Comment by Prajwal-SU** [comment]
Hi @tjanczak,
I have performed memory leak test for yolov11n model there was no leak memory, it stayed around 270 MB for 12hrs.

Pipeline-->GST_DEBUG=3 gst-launch-1.0 rtspsrc location=rtsp://10.90.9.149:32558/no_mask ! decodebin ! videoconvert ! capsfilter caps="video/x-raw,format=BGR" ! gvadetect model=yolo11n.xml device=GPU inference-interval=1 pre-process-backend=opencv ! gvawatermark ! videoconvert ! appsink max-buffers=1 drop=true

![Image](https://github.com/user-attachments/assets/eb294664-1be1-4f35-8436-6cf1886c7e4c)

[yolo11n.zip](https://github.com/user-attachments/files/20477445/yolo11n.zip)

**Comment by Prajwal-SU** [comment]
Hi @brmarkus and @nszczygl9 ,
I pulled the latest Docker image today. From my initial check, it looks like the memory leak has been resolved with the provided fix, so we can close the issue.

However, if you would like me to verify it again, I can recheck from my side and confirm once done.
